# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controller', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('uri', models.CharField(help_text='A device URI such as onewire://182377282', max_length=255)),
                ('slot', models.PositiveIntegerField(blank=True, help_text='The slot ID assigned paired with the Controller', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.Device')),
            ],
            options={
                'abstract': False,
            },
            bases=('device.device',),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='device.Device')),
            ],
            options={
                'abstract': False,
            },
            bases=('device.device',),
        ),
        migrations.AddField(
            model_name='device',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='controller.Controller'),
        ),
        migrations.AddField(
            model_name='device',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_device.device_set+', to='contenttypes.ContentType'),
        ),
    ]
