# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uri', models.CharField(help_text='Which address to connect to, e.g. http://10.42.42.10', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('alive', models.BooleanField(default=False, help_text='Whether this device has been online during the last few seconds.')),
            ],
        ),
    ]
